travis:
  secure:
    BINSTAR_TOKEN: rIBPNAB8InrVk/HEqT1qbf6QsR7Yjnc/SQ33VfvvWgPJfiT4mgwF9WM3LDhPnCIg/Q6MTXZqbimGEV5Ewlj4KsZuanAbBGq+0kKcece5vfWaktTu+BBbJc+SmBmKO5f+UyYY+0foEtmhPwLfdbe3KGo8/dwyd/laYWlfG9PslwtLEY+grvIqfW87y60eViEJ9TpF46oaf/jkSZGW1erExDOow4AV3+jFxkA5aZ9bicNzbCGwjqUyIoDE5pAOvktLrrxIt5k99ReRpki1iPRd7KHMd5N+dvB0qpbn9Lu5GsdOX45rfrZYFu/ArzO/XMr47tp7JB+YANHJhlWdN1FUW9X3oBMaDSSGf/apFEwFgjlBoRY73MAXnLypZxr/KnoLUcQ/udVwKcbPrR6a//Iww6ZN8HxmrAs0onM5z4xQ9fWYo96LnZ/LXVGbxvnANv9PuF8Sh9bqK+F4M2JjNDUvom7LLbCLD1UzFHRG32FDxcoezO9IUsy6NbimRb3ERcbJ/W3wxCPf7Q6JmvvcDZB6EFOlAbIJ6BahDpjS399Gs+zlFPblbV70xmJfo7gNWwCP90mRsQpj2uZziyz7AjS4zFjeY4Ldd6QGL6eo9zRf9uLfsOBzXoHQz3o4n02yLcnPRREsucm/v5FaNObr/1Uf5A0UPuKfaRdxOmOB2olO+do=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
